name: mightyvpn
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  nb_utils: ^5.0.6
  flutter_vector_icons: ^2.0.0
  image_picker: ^0.8.7+1
  cached_network_image: ^3.2.3
  http: ^0.13.5
  package_info: ^2.0.2
  url_launcher: ^6.1.10
  share_plus: ^6.3.1
  google_fonts: ^4.0.3
  get_ip_address: ^0.0.5

  flutter_internet_speed_test: ^1.4.0

  speed_test_dart: ^1.0.4+1

  syncfusion_flutter_gauges: ^21.1.37
  percent_indicator: ^4.2.3
  device_info_plus: ^8.1.0

  #ads
  google_mobile_ads: ^2.4.0
  facebook_audience_network: ^1.0.1

  # Firebase
  firebase_core: ^2.9.0
  firebase_analytics: ^10.2.0
  firebase_crashlytics: ^3.1.0
  cloud_firestore: ^4.5.0

  flutter_localizations:
    sdk: flutter
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/opvn/
    - assets/flag/

